### ISSUE TITLE
Add width: max-content to select

### ISSUE THREAD

**Issue by NormandoHall** [pstanoev/simple-svelte-autocomplete#192]
If the dropdown item is more wide than dropdown, the background and color is truncated

As code has:

```css
  .autocomplete-list-item.selected {
    background-color: #2e69e2;
    color: #fff;
  }
```

![image](https://user-images.githubusercontent.com/2943127/210722537-41cb015f-e118-4158-8b11-1a920d348040.png)

With width:

```css
  .autocomplete-list-item.selected {
    background-color: #2e69e2;
    color: #fff;
    width: max-content;
  }
```

![image](https://user-images.githubusercontent.com/2943127/210722631-91ef3566-4159-46b5-bedb-9d52c29d5927.png)
